Send login succeed after on-boarding
kinfoundation/kin-ecosystem-android-sdk pull request #264
Opened 2019-02-05 12:41 UTC by OrenZak

#### Main purpose:
The developer now can use any of the SDK API's after login succeed response
#### Technical description:
- create a polling request for account balance and make sure he is ready.
- listen for account state on the login process
- added Kotlin
#### Documentation:
(Source/readme.md)

2019-02-06 10:02 UTC, doodyparizada requested changes

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/CoreCallback.kt
> +interface CoreCallback<T> {
can be in utils

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/PollingRequest.kt
> +    private fun poll(pollingIndex: Int): T {
I prefer while loop instead of recursion

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/PollingRequest.kt
> +        } catch (e: Exception) {
~Can there be a persistent error that doesn't need to be retried such as error 4xx?~

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/PollingRequest.kt
> +        request?.run(callback)
why `?`

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/PollingRequest.kt
> +        request = Request(pollingCallable)
Maybe Request can be initialized in `init`

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/Request.kt
> +        checkNotNull(callable, "callable")
not sure if throwing exception in ctor is good practice

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/Request.kt
> +        this.resultCallback = callback
maybe don't set `this` - this is a side effect

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/Request.kt
> +                future!!.cancel(mayInterruptIfRunning)
nullable

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/Request.kt
> +                future!!.cancel(mayInterruptIfRunning)
use `?`

2019-02-06 10:02 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/Request.kt
> +            mainHandler.post { resultCallback = null }
Why in main thread

2019-02-06 11:32 UTC, OrenZak commented on core/src/main/java/com/kin/ecosystem/core/CoreCallback.kt
> +interface CoreCallback<T> {
don't want it to be coupled with another module.

2019-02-06 12:23 UTC, OrenZak commented on core/src/main/java/com/kin/ecosystem/core/Request.kt
> +        checkNotNull(callable, "callable")
we don't need it at all since it's Kotlin null safety

2019-02-07 08:59 UTC, doodyparizada commented on core/src/main/java/com/kin/ecosystem/core/PollingRequest.kt
> +    private fun poll(pollingIndex: Int): T {
```
for (pollingIndex=0;  pollingIndex < pollingLimitIndex; pollingIndex++) {
Do stuff
}
```

2019-02-07 09:13 UTC, doodyparizada approved these changes

2019-02-07 09:13 UTC, merged